### ISSUE TITLE
WHERE clause gets placed after ORDER BY

### ISSUE THREAD

**Issue by cybre** [mladenb/sql-query-builder#1]
As far as I understand, the `WHERE` clauses are evaluated last, placing them at the last position in the query.
This causes an issue when an `ORDER BY` clause is present.
The `ORDER BY` clause will get placed before the `WHERE` clause, resulting in invalid SQL.

**Comment by mladenb** [comment]
You're right. In the ConsolidateWhereClauses() (in "DefaultSqlQueryBuilder/Extensions/SqlClauseExtensions.cs"), we first remove all the WHERE clauses using the method "clauses.RemoveAll()" and then we agreggate and add them (at the end), using "clauses.Add()", which is wrong, as you suggested. We should instead replace the last WHERE clause with the WHERE aggregate. The fix should be to replace the last WHERE clause with the aggregate.

If you already located and fixed that part, please create a pull request and I'll merge it. If you don't feel comfortable to do it, I'll fix it anyway and I can let you know when I do that, ok? :)
